spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8050
