spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres:5432/
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8070
services:
  gateway: 8080
